version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      # - image: docker:18.06.3-ce-git
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            python
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
