version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
