version: 2.1  # Update to version 2.1

jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:dind  # Consider a specific version for stability
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py

      - deploy:
          name: Publish application Docker image
          command: |
            echo "** Warning: Not storing credentials in plain text!**"
            # Use environment variables or orb for secure storage
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD  # Consider orb for login
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker tag dockerapp_dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest