version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      # - image: docker:17.05.0-ce-git
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update
            apk add --no-cache py-pip
            pip install docker-compose==1.29.2
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
